// frontend/src/entities/theme/ui/theme-toggle.vue
<script setup lang="ts">
import { Button } from '@/shared/ui';
import { useColorMode } from '@vueuse/core';
import { Moon, Sun } from 'lucide-vue-next'

const mode = useColorMode()

const changeTheme = () => mode.value = mode.value === 'light' ? 'dark' : "light"
</script>

<template>
  <Button size='icon-sm' variant='outline' @click="changeTheme">
    <Sun v-if="mode === 'light'" />
    <Moon v-if="mode === 'dark'" />
  </Button>
</template>

// frontend/src/entities/theme/ui/ThemeToggle.tsx
import { Moon, Sun, Monitor } from 'lucide-react'
import { ToggleGroup, ToggleGroupItem } from '@/shared/ui'
import { useTheme } from '../model/useTheme'
import { Theme } from '../model/types'

const themeItems = [
  {
    value: 'light',
    Icon: Sun,
    label: 'Светлая'
  },
  {
    value: 'dark',
    Icon: Moon,
    label: 'Темная'
  },
  {
    value: 'system',
    Icon: Monitor,
    label: 'Системная'
  }
] as const

export const ThemeToggle = () => {
  const { theme, changeTheme } = useTheme()

  const handleChangeTheme = (value: Theme) => {
    if (value) {
      changeTheme(value as Theme)
    }
  }

  return (
    <ToggleGroup
      size='sm'
      type='single'
      variant='outline'
      value={theme}
      onValueChange={handleChangeTheme}
    >
      {themeItems.map(({ value, label, Icon }) => (
        <ToggleGroupItem key={value} value={value} aria-label={label}>
          <Icon />
        </ToggleGroupItem>
      ))}
    </ToggleGroup>
  )
}
